name: todoey_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.3.2
  image_picker: ^1.0.7
  image_cropper: ^5.0.0
  #auto_route: ^7.8.4

  # Widgets
  flutter_staggered_grid_view: ^0.7.0
  flutter_quill: ^9.3.1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  google_nav_bar: ^5.0.6
  grock: ^0.5.6

  # Icons


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider: ^6.1.1
  flutter_animate: ^4.4.0
  modal_progress_hud_nsn: ^0.4.0
  intl: ^0.18.1
  build_runner: ^2.4.8
  #auto_route_generator: ^7.3.2


  # Databases
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  hive_generator: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  

flutter:

  uses-material-design: true

  assets:
    - assets/avatar.jpeg
    - assets/tiles/
  fonts:
    - family: DotGothic16
      fonts:
        - asset: fonts/DotGothic16-Regular.ttf
    - family: Micro5
      fonts:
        - asset: fonts/Micro5-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

