name: todoey_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.3.2
  image_picker: ^1.0.7
  image_cropper: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Widgets


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider: ^6.1.1
  flutter_animate: ^4.4.0
  modal_progress_hud_nsn: ^0.4.0
  intl: ^0.17.0
  build_runner: ^2.4.8


  # Databases
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  hive_generator: ^2.0.1

  

flutter:

  uses-material-design: true

  assets:
    - assets/avatar.jpeg

